---
- name: Make sure zsh and zplug are present
  homebrew:
    name:
      - zsh
      - zplug
    state: present

- name: Make sure variables are included
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Make sure directories are present
  file:
    path: '{{ config_path }}'
    state: directory

- name: Make sure config files are generated
  template:
    src: '{{ item.src }}'
    dest: '{{ config_path }}/{{ item.path }}'
  with_filetree: templates/zsh
  when: item.state == 'file'

- name: Make sure zshrc is present
  template:
    src: templates/.zshrc.j2
    dest: ~/.zshrc

- name: Make sure global .ignore is present
  template:
    src: templates/.ignore.j2
    dest: ~/.ignore

- name: Make sure to set brew zsh as default shell
  shell:
    dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
    chsh -s /usr/local/bin/zsh
  become: true
