---
- name: Make sure neovim is installed
  homebrew:
    name:
      - neovim
    state: present

- name: Make sure autoload directory exists
  file:
    path: '{{ autoload_path }}'
    state: directory

- include: vim_plug.yml
- include: python_venv.yml

- name: Create directories
  file:
    path: '{{ config_path }}/{{ item.path }}'
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Make sure config files are generated
  template:
    src: '{{ item.src }}'
    dest: '{{ config_path }}/{{ item.path }}'
  with_filetree: templates/
  when: item.state == 'file'

- name: Make sure plugins are installed
  shell:
    nvim +PlugInstall +qall

- name: Make sure vim-language-server is present
  npm:
    name: 'vim-language-server'
    global: true
